---
- name: Base set up
  hosts: all
  #Выполнять действия от root-пользователя
  become: yes
  tasks:
  #Установка текстового редактора nano и chrony
  - name: install softs on CentOS
    yum:
      name:
        - nano
        - chrony
      state: present
      update_cache: true
  
  #Отключение firewalld и удаление его из автозагрузки
  - name: Install firewalld
    yum:
      name: firewalld
      state: latest
    # notify:
    #   - start firewalld
  
  - name: start firewalld
    service:
      name: firewalld
      state: started
      enabled: yes
    become: yes
  # настраиваем необходимые порты на firewalld
  - name: enable 53
    firewalld:
      zone: public
      port: 53/tcp
      permanent: true
      state: enabled
    become: yes

  - name: enable 53
    firewalld:
      zone: public
      port: 53/udp
      permanent: true
      state: enabled
    become: yes
  
  - name: enable 80
    firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: enabled
    become: yes

  - name: enable 443
    firewalld:
      zone: public
      port: 443/tcp
      permanent: true
      state: enabled
    become: yes

  - name: enable 88
    firewalld:
      zone: public
      port: 88/tcp
      permanent: true
      state: enabled
    become: yes

  - name: enable 464
    firewalld:
      zone: public
      port: 464/tcp
      permanent: true
      state: enabled
    become: yes

  - name: enable 88
    firewalld:
      zone: public
      port: 88/udp
      permanent: true
      state: enabled
    become: yes

  - name: enable 464
    firewalld:
      zone: public
      port: 464/udp
      permanent: true
      state: enabled
    become: yes

  - name: enable 123
    firewalld:
      zone: public
      port: 123/udp
      permanent: true
      state: enabled
    become: yes

  - name: enable 389
    firewalld:
      zone: public
      port: 389/tcp
      permanent: true
      state: enabled
    become: yes

  - name: enable 636
    firewalld:
      zone: public
      port: 636/tcp
      permanent: true
      state: enabled
    become: yes

  - name: start reloaded
    service:
      name: firewalld
      state: reloaded
      enabled: yes
    become: yes

  #Отключение SElinux из автозагрузки
  #Будет применено после перезагрузки
  - name: disable SElinux
    selinux:
      state: disabled
  
  #Отключение SElinux до перезагрузки
  - name: disable SElinux now
    shell: setenforce 0

  #Установка временной зоны Европа/Москва    
  - name: Set up timezone
    timezone:
      name: "Asia/Vladivostok"
  
  #Запуск службы Chrony, добавление её в автозагрузку
  - name: enable chrony
    service:
      name: chronyd
      state: restarted
      enabled: true
  
  #Копирование файла /etc/hosts c правами root:root 0644
  - name: change /etc/hosts
    template:
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644
  
  #Установка клиента Freeipa
  - name: install module ipa-client
    yum:
      name:
        - freeipa-client
      state: present
      update_cache: true
  
 
  #Запуск скрипта добавления хоста к серверу
  - name: add host to ipa-server
    shell: echo -e "yes\nyes" | ipa-client-install --mkhomedir --domain=OTUS.LAN --server=ipa.otus.lan --no-ntp -p admin -w Passw0rd!